#!/usr/bin/env ruby
#
# Launches an IRb console with the Autumn environment loaded.

puts "setting APP_ROOT..."
APP_ROOT = File.expand_path("#{File.dirname(__FILE__)}/..")
$: << APP_ROOT

# Some code below is from Ruby on Rails and copyright (c) David Heinemeier
# Hansson.

irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

require 'optparse'
#options = { :irb => irb }
options = {}
OptionParser.new do |opt|
  opt.banner = "Usage: #{File.basename(__FILE__)} [options]"
  opt.on("--irb=[#{irb}]", 'Invoke a different irb.') { |v| options[:irb] = v }
  opt.parse!(ARGV)
end

require "irb"
require "irb/completion"
require "autumn/console_boot"

require 'autumn/genesis'
puts "Loading Autumn #{AUTUMN_VERSION}..."
if options[:irb] 
   #TODO: APP_ROOT wont be set here
   raise "Ooops! only default irb for now (option)"
else
   IRB.start
end
