#!/usr/bin/env ruby
#
# Runs Autumn from the command line. This script will not exit until all leaves
# have exited. To use this script as a daemon, see the script/daemon script.

APP_ROOT = File.expand_path("#{File.dirname(__FILE__)}/..")
$: << APP_ROOT

require 'rubygems'
require 'autumn/genesis'

puts "Loading Autumn #{AUTUMN_VERSION}"
Autumn::Genesis.new.boot!
